# Generated by Django 3.1.7 on 2021-04-03 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'polls',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400, null=True)),
                ('poll_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Choice', to='poll.poll')),
            ],
            options={
                'verbose_name': 'Вариант_ответа',
                'verbose_name_plural': 'Варианты_ответа',
                'db_table': 'choices',
            },
        ),
    ]
